#!/usr/bin/env python3
"""
Generate a consolidated profiling report from all pipeline stages.

This script reads the individual profiling reports generated by each stage
and creates a combined report showing the overall pipeline performance.
"""

import os
import sys
from pathlib import Path

def parse_profiling_csv(filepath):
    """Parse a profiling CSV file and return the data."""
    if not os.path.exists(filepath):
        return None
    
    data = []
    with open(filepath, 'r') as f:
        lines = f.readlines()
        if len(lines) < 2:
            return None
        
        # Skip header
        for line in lines[1:]:
            parts = line.strip().split(',')
            if len(parts) >= 6:
                data.append({
                    'function': parts[0],
                    'calls': int(parts[1]),
                    'total_time': float(parts[2]),
                    'avg_time': float(parts[3]),
                    'min_time': float(parts[4]),
                    'max_time': float(parts[5])
                })
    
    return data

def generate_consolidated_report(output_folder):
    """Generate a consolidated report from all profiling data."""
    
    # Create profiling subfolder path
    profiling_folder = os.path.join(output_folder, "Profiling")
    
    # Define the stages and their report files (with new naming convention)
    stages = [
        ('Decomposer', 'Mesh Decomposition'),
        ('Adjaceny', 'Adjacency Computation'),
        ('Path', 'Path Ordering'),
        ('Onion3d', 'Onion Layer Processing')
    ]
    
    report_lines = []
    report_lines.append("="*100)
    report_lines.append("CONSOLIDATED PERFORMANCE PROFILING REPORT")
    report_lines.append("="*100)
    report_lines.append("")
    
    stage_summaries = []
    all_functions = []
    
    # Parse each stage's data
    for stage_name, stage_display in stages:
        csv_path = os.path.join(profiling_folder, f"Profiling_{stage_name}.csv")
        data = parse_profiling_csv(csv_path)
        
        if data:
            stage_total = sum(d['total_time'] for d in data)
            stage_calls = sum(d['calls'] for d in data)
            stage_summaries.append({
                'name': stage_display,
                'total_time': stage_total,
                'calls': stage_calls,
                'data': data
            })
            all_functions.extend(data)
    
    if not stage_summaries:
        print("No profiling data found. Run with --debug flag to enable profiling.")
        return
    
    # Overall summary
    total_time = sum(s['total_time'] for s in stage_summaries)
    total_calls = sum(s['calls'] for s in stage_summaries)
    
    report_lines.append(f"Total Pipeline Execution Time: {total_time:.3f}s")
    report_lines.append(f"Total Function Calls: {total_calls:,}")
    report_lines.append("")
    
    # Stage breakdown
    report_lines.append("PIPELINE STAGE BREAKDOWN:")
    report_lines.append("-"*100)
    report_lines.append(f"{'Stage':<35} {'Time (s)':>15} {'% of Total':>15} {'Calls':>15}")
    report_lines.append("-"*100)
    
    for stage in stage_summaries:
        percent = (stage['total_time'] / total_time * 100) if total_time > 0 else 0
        report_lines.append(
            f"{stage['name']:<35} "
            f"{stage['total_time']:>15.3f} "
            f"{percent:>14.2f}% "
            f"{stage['calls']:>15,}"
        )
    
    report_lines.append("-"*100)
    report_lines.append("")
    
    # Top functions across all stages
    report_lines.append("TOP 20 FUNCTIONS ACROSS ALL STAGES:")
    report_lines.append("-"*100)
    report_lines.append(f"{'Function Name':<45} {'Calls':>10} {'Total(s)':>12} {'Avg(ms)':>12}")
    report_lines.append("-"*100)
    
    # Sort by total time
    all_functions.sort(key=lambda x: x['total_time'], reverse=True)
    for func in all_functions[:20]:
        report_lines.append(
            f"{func['function']:<45} "
            f"{func['calls']:>10} "
            f"{func['total_time']:>12.3f} "
            f"{func['avg_time']:>12.3f}"
        )
    
    report_lines.append("-"*100)
    report_lines.append("")
    
    # Optimization recommendations
    report_lines.append("OPTIMIZATION RECOMMENDATIONS:")
    report_lines.append("-"*100)
    report_lines.append("")
    
    # Find the slowest stage
    slowest_stage = max(stage_summaries, key=lambda x: x['total_time'])
    report_lines.append(f"1. Focus on: {slowest_stage['name']}")
    stage_percent = (slowest_stage['total_time'] / total_time * 100) if total_time > 0 else 0
    report_lines.append(f"   This stage consumes {stage_percent:.1f}% of total pipeline time.")
    report_lines.append("")
    
    # Find the slowest function overall
    if all_functions:
        slowest_func = all_functions[0]
        func_percent = (slowest_func['total_time'] / total_time * 100) if total_time > 0 else 0
        report_lines.append(f"2. Optimize: {slowest_func['function']}")
        report_lines.append(f"   This function alone takes {slowest_func['total_time']:.3f}s ({func_percent:.1f}% of total).")
        report_lines.append(f"   Called {slowest_func['calls']} times, averaging {slowest_func['avg_time']:.3f}ms per call.")
        report_lines.append("")
    
    # Find functions called very frequently
    frequent_funcs = sorted(all_functions, key=lambda x: x['calls'], reverse=True)
    if frequent_funcs:
        most_frequent = frequent_funcs[0]
        report_lines.append(f"3. Consider caching: {most_frequent['function']}")
        report_lines.append(f"   Called {most_frequent['calls']:,} times.")
        report_lines.append(f"   If results are reusable, caching could save {most_frequent['total_time']:.3f}s.")
        report_lines.append("")
    
    # Find functions with high variance (max >> avg)
    high_variance = [f for f in all_functions if f['max_time'] > f['avg_time'] * 5]
    if high_variance:
        report_lines.append("4. Investigate variance in these functions:")
        for func in high_variance[:3]:
            report_lines.append(f"   - {func['function']}")
            report_lines.append(f"     Avg: {func['avg_time']:.3f}ms, Max: {func['max_time']:.3f}ms")
        report_lines.append("   High variance may indicate input-dependent performance.")
        report_lines.append("")
    
    report_lines.append("="*100)
    report_lines.append("")
    report_lines.append("For detailed stage-specific reports, see:")
    for stage_name, _ in stages:
        txt_path = f"Profiling/{stage_name}_profiling.txt"
        if os.path.exists(os.path.join(profiling_folder, f"Profiling_{stage_name}.txt")):
            report_lines.append(f"  - Profiling/Profiling_{stage_name}.txt")
    report_lines.append("")
    report_lines.append("See PROFILING_GUIDE.md for help interpreting these results.")
    report_lines.append("="*100)
    
    # Print report
    report = "\n".join(report_lines)
    print(report)
    
    # Save report in the Profiling subfolder
    os.makedirs(profiling_folder, exist_ok=True)
    output_path = os.path.join(profiling_folder, "Profiling_Report.txt")
    with open(output_path, 'w') as f:
        f.write(report)
    
    print(f"\nConsolidated report saved to: {output_path}")

def main():
    """Main entry point."""
    output_folder = "DecompositionOUTPUT"
    
    if len(sys.argv) > 1:
        output_folder = sys.argv[1]
    
    if not os.path.exists(output_folder):
        print(f"Error: Output folder '{output_folder}' does not exist.")
        sys.exit(1)
    
    generate_consolidated_report(output_folder)

if __name__ == "__main__":
    main()

